[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.34"
serde = "1.0.196"
serde_derive = {version = "1.0.196"}
serde_json = "1.0.113"
sha2 = "0.10.8"