[package]
name = "wasm_snake"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
target = ["wasm32-unknown-unknown"]


[dependencies]
stdweb = "0.4.7"
